In [2]:
import numpy as np
a = np.arange(15)
print(a, type(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] <class 'numpy.ndarray'>


In [3]:
a.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a = a.reshape(3, 5)

In [5]:
"""
ndarray.shape
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. 
For a matrix with n rows and m columns, shape will be (n,m).
The length of the shape tuple is therefore the number of axes, ndim.
"""
a.shape

(3, 5)

In [6]:
"""
ndarray.ndim
the number of axes (dimensions) of the array.
"""
a.ndim

2

In [7]:
"""
ndarray.size
the total number of elements of the array. This is equal to the product of the elements of shape.
"""
a.size

15

In [8]:
"""
ndarray.dtype
an object describing the type of the elements in the array. 
One can create or specify dtype’s using standard Python types. 
Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
"""
a.dtype

dtype('int32')

In [9]:
a.dtype.name

'int32'

In [10]:
type(a)

numpy.ndarray

In [11]:
a.itemsize

4

In [12]:
"""
ndarray.itemsize
the size in bytes of each element of the array. 
For example, an array of elements of type float64 has itemsize 8 (=64/8), 
while one of type complex32 has itemsize 4 (=32/8). 
It is equivalent to ndarray.dtype.itemsize.
"""
a.dtype.itemsize

4

In [13]:
a.dtype.itemsize == a.itemsize

True

In [14]:
"""
ndarray.data
the buffer containing the actual elements of the array. 
Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.
"""
a.data

In [15]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [16]:
type(b)

numpy.ndarray

In [18]:
"""
Array Creation
"""
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [19]:
a.dtype

dtype('int32')

In [21]:
b = np.array([1.2, 3.5, .2])
b

array([1.2, 3.5, 0.2])

In [22]:
b.dtype

dtype('float64')

In [23]:
a = np.array(1,2,3,4) 

ValueError: only 2 non-keyword arguments accepted

In [25]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [26]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [28]:
"""
The function zeros creates an array full of zeros, the function ones creates an array full of ones, 
and the function empty creates an array whose initial content is random and depends on the state of the memory. 
By default, the dtype of the created array is float64.
"""
d = np.zeros((3, 4))
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
d.dtype

dtype('float64')

In [32]:
e = np.ones((2, 3, 4), dtype=np.int16)
e

(array([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=int16), dtype('int16'))

In [33]:
f = np.empty((2, 3))
f, f.dtype

(array([[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]), dtype('float64'))

In [34]:
from numpy import pi
pi

3.141592653589793

In [35]:
np.linspace(0, 2, 9)  # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [39]:
x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [41]:
f = np.sin(x)

In [42]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [43]:
np.arange(6).reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [45]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [46]:
"""
Basic Operations
"""
a = np.array([20,30,40,50])

In [47]:
b = np.arange( 4 )
a, b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [48]:
a-b

array([20, 29, 38, 47])

In [53]:
b**2, b*2, (b*2).dtype

(array([0, 1, 4, 9], dtype=int32), array([0, 2, 4, 6]), dtype('int32'))

In [54]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [55]:
a<35

array([ True,  True, False, False])

In [57]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A * B     # elementwise product

array([[2, 0],
       [0, 4]])

In [58]:
A @ B    # matrix product

array([[5, 4],
       [3, 4]])

In [59]:
A.dot(B)    # matrix product

array([[5, 4],
       [3, 4]])

In [62]:
a = np.ones((2, 3), dtype=int)
b = np.random.random((2, 3))
a, b

(array([[1, 1, 1],
        [1, 1, 1]]), array([[0.99564768, 0.65277463, 0.6076121 ],
        [0.20177756, 0.22978527, 0.39559233]]))

In [63]:
a * 3

array([[3, 3, 3],
       [3, 3, 3]])

In [64]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [67]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [68]:
b += a
b

array([[5.99564768, 5.65277463, 5.6076121 ],
       [5.20177756, 5.22978527, 5.39559233]])

In [69]:
a += b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [70]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype

dtype('float64')

In [71]:
c = a + b
c, c.dtype

(array([1.        , 2.57079633, 4.14159265]), dtype('float64'))

In [72]:
d = np.exp(c*1j)
d, d.dtype.name

(array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
        -0.54030231-0.84147098j]), 'complex128')

In [73]:
a = np.random.random((2, 3))
a

array([[0.58066325, 0.64267901, 0.00285102],
       [0.27220093, 0.76098932, 0.6277327 ]])

In [74]:
a.sum

<function ndarray.sum>

In [75]:
a.sum()

2.88711624128908

In [76]:
a.min(), a.max()

(0.00285102034845075, 0.7609893239737564)

In [77]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
b.sum(axis=0)    # sum of each column

array([12, 15, 18, 21])

In [79]:
b.min(axis=1)    # sum of each row

array([0, 4, 8])

In [80]:
b.cumsum(axis=1)    # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [81]:
B = np.arange(3)
B

array([0, 1, 2])

In [82]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [83]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [84]:
C = np.array([2., -1., 4.])
C

array([ 2., -1.,  4.])

In [85]:
np.add(B, C)

array([2., 0., 6.])

In [86]:
"""
Indexing, Slicing and Iterating
One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.
"""
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [87]:
a[2], a[2:5]

(8, array([ 8, 27, 64], dtype=int32))

In [88]:
a[:6:2] = -1000

In [89]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [90]:
a[::-1]   # a copy, source not change

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [91]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [103]:
for i in a:
    print(i**(1/3))

nan
1.0
nan
3.0
nan
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


c:\users\kid\envs\python3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [105]:
for i in a:
    print(np.sign(i) * (np.abs(i)) ** (1 / 3))

-9.999999999999998
1.0
-9.999999999999998
3.0
-9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [107]:
def f(x, y):
    return 10*x + y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [108]:
b[2, 3]

23

In [109]:
b[0:5, 1]    # each row in the second column of b   

array([ 1, 11, 21, 31, 41])

In [110]:
b[:, 1]

array([ 1, 11, 21, 31, 41])

In [111]:
b[1:3, : ]   # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [112]:
b[-1]   # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

In [113]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
                [[100,101,102],
                 [110,112,113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [114]:
c.shape

(2, 2, 3)

In [116]:
c[1,...]    # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [117]:
c[...,2]    # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

In [118]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [119]:
"""
Iterating over multidimensional arrays is done with respect to the first axis:
"""
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [120]:
"""
However, if one wants to perform an operation on each element in the array, 
one can use the flat attribute which is an iterator over all the elements of the array:
"""
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
