In [1]:
import numpy as np
a = np.floor(10*np.random.random((3,4)))
a

array([[3., 9., 9., 1.],
       [0., 4., 0., 9.],
       [8., 6., 6., 1.]])

In [2]:
a.shape

(3, 4)

In [3]:
"""
The shape of an array can be changed with various commands. 
Note that the following three commands all return a modified array, but do not change the original array:
"""
a.ravel()    # returns the array, flattened

array([3., 9., 9., 1., 0., 4., 0., 9., 8., 6., 6., 1.])

In [4]:
a

array([[3., 9., 9., 1.],
       [0., 4., 0., 9.],
       [8., 6., 6., 1.]])

In [5]:
a.reshape(6, 2)

array([[3., 9.],
       [9., 1.],
       [0., 4.],
       [0., 9.],
       [8., 6.],
       [6., 1.]])

In [6]:
a.T    # returns the array, transposed

array([[3., 0., 8.],
       [9., 4., 6.],
       [9., 0., 6.],
       [1., 9., 1.]])

In [7]:
a.T.shape, a.shape

((4, 3), (3, 4))

In [8]:
a

array([[3., 9., 9., 1.],
       [0., 4., 0., 9.],
       [8., 6., 6., 1.]])

In [10]:
"""
The reshape function returns its argument with a modified shape, 
whereas the ndarray.resize method modifies the array itself:
"""
a.resize((2, 6))
a

array([[3., 9., 9., 1., 0., 4.],
       [0., 9., 8., 6., 6., 1.]])

In [13]:
"""
If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
"""
a.reshape(3, -1)

array([[3., 9., 9., 1.],
       [0., 4., 0., 9.],
       [8., 6., 6., 1.]])

In [17]:
"""
Stacking together different arrays
Several arrays can be stacked together along different axes:
"""
a = np.floor(10*np.random.random((2,2)))
a

array([[5., 3.],
       [2., 4.]])

In [20]:
b = np.floor(10*np.random.random((2,2)))
b

array([[0., 7.],
       [2., 0.]])

In [21]:
np.vstack((a, b))

array([[5., 3.],
       [2., 4.],
       [0., 7.],
       [2., 0.]])

In [22]:
np.hstack((a,b))

array([[5., 3., 0., 7.],
       [2., 4., 2., 0.]])

In [23]:
"""
The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:
"""
from numpy import newaxis
np.column_stack((a, b))    # with 2D arrays

array([[5., 3., 0., 7.],
       [2., 4., 2., 0.]])

In [24]:
a = np.array([4., 2.])
b = np.array([3., 8.])
a, b

(array([4., 2.]), array([3., 8.]))

In [25]:
np.column_stack((a, b))    # return a 2D array

array([[4., 3.],
       [2., 8.]])

In [26]:
np.hstack((a, b))        # the result is diffferent

array([4., 2., 3., 8.])

In [27]:
a[:,newaxis]               # this allows to have a 2D columns vector

array([[4.],
       [2.]])

In [28]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [29]:
np.hstack((a[:,newaxis],b[:,newaxis]))   # the result is the same

array([[4., 3.],
       [2., 8.]])

In [31]:
"""
On the other hand, the function row_stack is equivalent to vstack for any input arrays.
In fact, row_stack is an alias for vstack:
"""
np.column_stack is np.hstack, np.row_stack is np.vstack

(False, True)

In [32]:
"""
In complex cases, r_ and c_ are useful for creating arrays by stacking numbers along one axis. 
They allow the use of range literals (“:”)
"""
np.r_[1:4, 0, 4]

array([1, 2, 3, 0, 4])

In [33]:
"""
Splitting one array into several smaller ones
Using hsplit, you can split an array along its horizontal axis, 
either by specifying the number of equally shaped arrays to return, 
or by specifying the columns after which the division should occur:
"""
a = np.floor(10*np.random.random((2,12)))
a

array([[7., 4., 8., 7., 8., 2., 3., 0., 3., 5., 2., 1.],
       [5., 4., 4., 0., 4., 0., 8., 3., 8., 8., 2., 0.]])

In [34]:
np.hsplit(a, 3)    # split a into 3

[array([[7., 4., 8., 7.],
        [5., 4., 4., 0.]]), array([[8., 2., 3., 0.],
        [4., 0., 8., 3.]]), array([[3., 5., 2., 1.],
        [8., 8., 2., 0.]])]

In [35]:
np.hsplit(a,(3,4))   # Split a after the third and the fourth column

[array([[7., 4., 8.],
        [5., 4., 4.]]), array([[7.],
        [0.]]), array([[8., 2., 3., 0., 3., 5., 2., 1.],
        [4., 0., 8., 3., 8., 8., 2., 0.]])]

In [ ]:
"""
vsplit splits along the vertical axis, and array_split allows one to specify along which axis to split.
"""