In [1]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
b = a    # no new object is created

In [4]:
b is a   # a and b are two names for the same ndarray object

True

In [5]:
b.shape

(12,)

In [6]:
b.shape = 3, 4

In [7]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
"""
Different array objects can share the same data. 
The view method creates a new array object that looks at the same data.
"""
c = a.view()
c, c is a

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), False)

In [11]:
c.base is a     # c is a view of the data owned by a

True

In [12]:
c.flags.owndata

False

In [13]:
c.shape = 2, 6    # a's shape doesn't change

In [14]:
a.shape

(3, 4)

In [15]:
c[0,4] = 1234    # a's data changes
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [16]:
"""
Slicing an array returns a view of it:
"""
s = a[ : , 1:3] 
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [17]:
s[:] = 10
s, a

(array([[10, 10],
        [10, 10],
        [10, 10]]), array([[   0,   10,   10,    3],
        [1234,   10,   10,    7],
        [   8,   10,   10,   11]]))

In [18]:
"""
The copy method makes a complete copy of the array and its data.
"""
d = a.copy()
d, d is a, d.base is a

(array([[   0,   10,   10,    3],
        [1234,   10,   10,    7],
        [   8,   10,   10,   11]]), False, False)

In [19]:
d[0, 0] = 9999
d

array([[9999,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [20]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [21]:
a = np.arange(int(1e8))
a

array([       0,        1,        2, ..., 99999997, 99999998, 99999999])

In [22]:
len(a)

100000000

In [23]:
b = a[:100].copy()
b, len(b)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]), 100)

In [24]:
del a

In [ ]:
"""
Functions and Methods Overview¶
https://numpy.org/devdocs/reference/routines.html#routines for NumPy functions and methods
"""
