## Tutorial from:
[101 NumPy Exercises for Data Analysis (Python)](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)
[101 NumPy Exercises for Data Analysis (Python) CN](https://www.numpy.org.cn/article/advanced/numpy_exercises_for_data_analysis.html)

### 1. Import numpy as np and see the version
Difficulty Level: L1    
Q. Import numpy as `np` and print the version number.

In [1]:
import numpy as np
np.__version__

'1.14.0'

### 2. How to create a 1D array?
Difficulty Level: L1

Q. Create a 1D array of numbers from 0 to 9

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3. How to create a boolean array?
Difficulty Level: L1

Q. Create a 3×3 numpy array of all True’s

In [3]:
np.full((3, 3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 4. How to extract items that satisfy a given condition from 1D array?
Difficulty Level: L1

Q. Extract all odd numbers from arr

Input:
> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Output:
> array([1, 3, 5, 7, 9])

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

### 5. How to replace items that satisfy a condition with another value in numpy array?
Difficulty Level: L1

Q. Replace all odd numbers in arr with -1

Input:
> arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

> array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
# solution 1, create a new array
arr = np.arange(10)
np.where(arr % 2 == 1, -1, arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [8]:
# solution 2, change original array
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 6. How to replace items that satisfy a condition without affecting the original array?
Difficulty Level: L2

Q. Same at #5

A. solution 1 in #5

### 7. How to reshape an array?
Difficulty Level: L1

Q. Convert a 1D array to a 2D array with 2 rows

In [9]:
arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 8. How to stack two arrays vertically?
Difficulty Level: L2

Q. Stack arrays a and b vertically

Input

> a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

Desired Output:

> array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [10]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

In [11]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
# solution 1
np.vstack((a, b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
# solution 2
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
# solution 3
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 9. How to stack two arrays horizontally?
Difficulty Level: L2

Q. Stack the arrays a and b horizontally.

Input

> a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

Desired Output:

> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [16]:
# solution 1
np.hstack((a, b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [17]:
# solution 2
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [18]:
# solution 3
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 10. How to generate custom sequences in numpy without hardcoding?
Difficulty Level: L2

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:
> a = np.array([1,2,3])

Desired Output:

> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [19]:
a = np.array([1, 2, 3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [20]:
np.tile(a, 3), np.c_[np.repeat(a, 3), np.tile(a, 3)]

(array([1, 2, 3, 1, 2, 3, 1, 2, 3]), array([[1, 1],
        [1, 2],
        [1, 3],
        [2, 1],
        [2, 2],
        [2, 3],
        [3, 1],
        [3, 2],
        [3, 3]]))

### 11. How to get the common items between two python numpy arrays?
Difficulty Level: L2

Q. Get the common items between a and b

Input:
    
> a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:
> array([2, 4])

In [22]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
np.intersect1d(a, b)

array([2, 4])

### 12. How to remove from one array those items that exist in another?
Difficulty Level: L2

Q. From array a remove all items present in array b

Input:

> a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

Desired Output:
> array([1,2,3,4])

In [23]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

### 13. How to get the positions where elements of two arrays match?
Difficulty Level: L2

Q. Get the positions where elements of a and b match

Input:

> a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:

> (array([1, 3, 5, 7]),)

In [24]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

### 14. How to extract all numbers between a given range from a numpy array?
Difficulty Level: L2

Q. Get all items between 5 and 10 from a.

Input:

> a = np.array([2, 6, 1, 9, 10, 3, 27])
Desired Output:

> (array([6, 9, 10]),)

In [26]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
# solution 1:
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [29]:
# solution 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [30]:
# solution 3:
a[(a>=5)&(a<=10)]

array([ 5,  6,  7,  8,  9, 10])

### 15. How to make a python function that handles scalars to work on numpy arrays?
Difficulty Level: L2

Q. Convert the function maxx that works on two scalars, to work on two arrays.

Input:
```
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5
```
Desired Output:
```
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
```

In [31]:
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y
    
pair_max = np.vectorize(maxx, otypes=[float])
    
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

### 16. How to swap two columns in a 2d numpy array?
Difficulty Level: L2

Q. Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)
arr

In [32]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
arr[:, [1, 0, 2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

### 17. How to swap two rows in a 2d numpy array?
Difficulty Level: L2

Q. Swap rows 1 and 2 in the array arr:

arr = np.arange(9).reshape(3,3)
arr

In [37]:
arr[[1, 0, 2],]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

### 18. How to reverse the rows of a 2D array?
Difficulty Level: L2

Q. Reverse the rows of a 2D array arr.

arr = np.arange(9).reshape(3,3)
arr

In [39]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### 19. How to reverse the columns of a 2D array?
Difficulty Level: L2

Q. Reverse the columns of a 2D array arr.

Input
arr = np.arange(9).reshape(3,3)
arr

In [41]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### 20. How to create a 2D array containing random floats between 5 and 10?
Difficulty Level: L2

Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [42]:
# solution 1:
np.random.randint(low=5, high=10, size=(5, 3))

array([[8, 5, 8],
       [7, 6, 8],
       [7, 7, 9],
       [9, 9, 8],
       [8, 6, 8]])

In [43]:
np.random.random((5,3))

array([[0.05645694, 0.84095782, 0.8715416 ],
       [0.10016586, 0.72497086, 0.27862796],
       [0.0805145 , 0.36599203, 0.82503575],
       [0.84296479, 0.68157268, 0.02920121],
       [0.58005375, 0.91210385, 0.69709714]])

In [45]:
rand_arr = np.random.randint(5, 10, (5, 3)) + np.random.random((5, 3))
rand_arr

array([[6.76063074, 6.10111106, 6.30344704],
       [7.50545975, 8.16620074, 9.83144955],
       [9.18699753, 8.94844555, 5.37602393],
       [6.7626081 , 5.90523573, 7.71080527],
       [5.66973128, 5.7535864 , 8.1872139 ]])

In [46]:
# solution 2:
np.random.uniform(5, 10, (5, 3))

array([[9.55381935, 9.66319677, 5.49738345],
       [6.36770889, 7.66767771, 5.99047669],
       [9.70827981, 7.99003392, 6.18097961],
       [7.56857208, 6.91281341, 7.95757868],
       [7.32580059, 6.44225904, 9.37686953]])

### 21. How to print only 3 decimal places in python numpy array?
Difficulty Level: L1

Q. Print or show only 3 decimal places of the numpy array rand_arr.

In [48]:
rand_arr = np.random.random((5, 3))
rand_arr

array([[0.16363538, 0.86880584, 0.13915392],
       [0.9721878 , 0.02512411, 0.61782219],
       [0.47816954, 0.848057  , 0.42962925],
       [0.08054339, 0.41528621, 0.5820659 ],
       [0.24319646, 0.8360994 , 0.03503561]])

In [51]:
np.set_printoptions(precision=3)
rand_arr

array([[0.164, 0.869, 0.139],
       [0.972, 0.025, 0.618],
       [0.478, 0.848, 0.43 ],
       [0.081, 0.415, 0.582],
       [0.243, 0.836, 0.035]])

### 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
Difficulty Level: L1

Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

In [52]:
np.random.random((5, 3))

array([[0.048, 0.528, 0.633],
       [0.437, 0.391, 0.242],
       [0.983, 0.239, 0.832],
       [0.699, 0.023, 0.644],
       [0.716, 0.97 , 0.057]])

In [68]:
np.set_printoptions()
np.random.random((5, 3))

array([[0.382, 0.036, 0.89 ],
       [0.981, 0.06 , 0.891],
       [0.577, 0.742, 0.63 ],
       [0.582, 0.02 , 0.21 ],
       [0.545, 0.769, 0.251]])

In [69]:
np.random.seed(100)

In [72]:
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[8.162e-04, 2.741e-04, 4.317e-04],
       [9.400e-04, 8.176e-04, 3.361e-04],
       [1.754e-04, 3.728e-04, 5.689e-06]])

In [73]:
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000816, 0.000274, 0.000432],
       [0.00094 , 0.000818, 0.000336],
       [0.000175, 0.000373, 0.000006]])

### 23. How to limit the number of items printed in output of numpy array?
Difficulty Level: L1

Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [74]:
np.set_printoptions(threshold=6)
np.arange(10)

array([0, 1, 2, ..., 7, 8, 9])

### 24. How to print the full numpy array without truncating
Difficulty Level: L1

Q. Print the full numpy array a without truncating.

In [76]:
np.set_printoptions(threshold=np.nan)

In [77]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
Difficulty Level: L2

Q. Import the iris dataset keeping the text intact.

In [78]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

### 26. How to extract a particular column from 1D array of tuples?
Difficulty Level: L2

Q. Extract the text column species from the 1D iris imported in previous question.

In [81]:
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
iris_1d.shape

c:\users\kid\envs\python3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


(150,)

In [83]:
species = np.array([row[4] for row in iris_1d])
species[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

### 27. How to convert a 1d array of tuples to a 2d numpy array?
Difficulty Level: L2

Q. Convert the 1D iris to 2D array iris_2d by omitting the species text field.

In [85]:
# solution 1:
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [86]:
# solution 2:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

### 28. How to compute the mean, median, standard deviation of a numpy array?
Difficulty: L1

Q. Find the mean, median, standard deviation of iris's sepallength (1st column)

In [87]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength[:5]

array([5.1, 4.9, 4.7, 4.6, 5. ])

In [89]:
mn, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
mn, med, sd

(5.843333333333334, 5.8, 0.8253012917851409)

### 29. How to normalize an array so the values range exactly between 0 and 1?
Difficulty: L2

Q. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

In [91]:
# solution 1:
smax, smin = sepallength.max(), sepallength.min()
smax, smin

(7.9, 4.3)

In [92]:
(sepallength-smin)/(smax-smin)

array([0.222222, 0.166667, 0.111111, 0.083333, 0.194444, 0.305556,
       0.083333, 0.194444, 0.027778, 0.166667, 0.305556, 0.138889,
       0.138889, 0.      , 0.416667, 0.388889, 0.305556, 0.222222,
       0.388889, 0.222222, 0.305556, 0.222222, 0.083333, 0.222222,
       0.138889, 0.194444, 0.194444, 0.25    , 0.25    , 0.111111,
       0.138889, 0.305556, 0.25    , 0.333333, 0.166667, 0.194444,
       0.333333, 0.166667, 0.027778, 0.222222, 0.194444, 0.055556,
       0.027778, 0.194444, 0.222222, 0.138889, 0.222222, 0.083333,
       0.277778, 0.194444, 0.75    , 0.583333, 0.722222, 0.333333,
       0.611111, 0.388889, 0.555556, 0.166667, 0.638889, 0.25    ,
       0.194444, 0.444444, 0.472222, 0.5     , 0.361111, 0.666667,
       0.361111, 0.416667, 0.527778, 0.361111, 0.444444, 0.5     ,
       0.555556, 0.5     , 0.583333, 0.638889, 0.694444, 0.666667,
       0.472222, 0.388889, 0.333333, 0.333333, 0.416667, 0.472222,
       0.305556, 0.472222, 0.666667, 0.555556, 0.361111, 0.333

In [94]:
smax - smin == sepallength.ptp(), sepallength.ptp()

(True, 3.6000000000000005)

### 30. How to compute the softmax score?
Difficulty Level: L3

Q. Compute the softmax score of sepallength.

In [95]:
def softmax(x):
    """Compute softmax values for each sets of scores in x.
    https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python"""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)
softmax(sepallength)

array([0.00222 , 0.001817, 0.001488, 0.001346, 0.002008, 0.002996,
       0.001346, 0.002008, 0.001102, 0.001817, 0.002996, 0.001644,
       0.001644, 0.000997, 0.00447 , 0.004044, 0.002996, 0.00222 ,
       0.004044, 0.00222 , 0.002996, 0.00222 , 0.001346, 0.00222 ,
       0.001644, 0.002008, 0.002008, 0.002453, 0.002453, 0.001488,
       0.001644, 0.002996, 0.002453, 0.003311, 0.001817, 0.002008,
       0.003311, 0.001817, 0.001102, 0.00222 , 0.002008, 0.001218,
       0.001102, 0.002008, 0.00222 , 0.001644, 0.00222 , 0.001346,
       0.002711, 0.002008, 0.01484 , 0.008144, 0.013428, 0.003311,
       0.009001, 0.004044, 0.007369, 0.001817, 0.009947, 0.002453,
       0.002008, 0.00494 , 0.005459, 0.006033, 0.003659, 0.010994,
       0.003659, 0.00447 , 0.006668, 0.003659, 0.00494 , 0.006033,
       0.007369, 0.006033, 0.008144, 0.009947, 0.01215 , 0.010994,
       0.005459, 0.004044, 0.003311, 0.003311, 0.00447 , 0.005459,
       0.002996, 0.005459, 0.010994, 0.007369, 0.003659, 0.003

### 31. How to find the percentile scores of a numpy array?
Difficulty Level: L1

Q. Find the 5th and 95th percentile of iris's sepallength

In [96]:
np.percentile(sepallength, q=[5, 95])

array([4.6  , 7.255])

In [100]:
np.percentile(sepallength, q=[0, 100])

array([4.3, 7.9])

### 32. How to insert values at random positions in an array?
Difficulty Level: L2

Q. Insert np.nan values at 20 random positions in iris_2d dataset

In [102]:
# solution 1:
i, j = np.where(iris_2d)
# i, j contain the row numbers and column numbers of 600 elements of iris_x
np.random.seed(100)
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan
iris_2d[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [nan, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [109]:
# solution 2:
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_2d[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [nan, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, nan, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

### 33. How to find the position of missing values in numpy array?
Difficulty Level: L2

Q. Find the number and position of missing values in iris_2d's sepallength (1st column)

In [111]:
print("Number of missing values: \n", np.isnan(iris_2d[:,0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))

Number of missing values: 
 8
Position of missing values: 
 (array([ 1, 14, 19, 23, 34, 79, 87, 96], dtype=int64),)


In [112]:
np.random.randn(6, 4)

array([[ 0.598291, -1.750374,  0.133306, -1.31521 ],
       [-0.937495,  0.384211, -0.66168 ,  2.587856],
       [-1.083102, -2.066341, -1.270645, -2.095724],
       [-2.137406,  0.915849,  0.592576,  0.037958],
       [ 0.371968,  0.359754, -0.140396, -0.443739],
       [ 0.56877 ,  0.538489,  1.315574,  1.478978]])